#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     AutoIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     PaddleLIGHT,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Includes consts.c and robot.c, as well
// Drivers can be found in Google Drive
#include "actions.h"
int driveTurns;
#define options 3
int numberOfGoals;
int
/**
* returns true if the robot is aligned with the beacon
*/
bool aligned(){
	return SensorValue[AutoIR] == irZone;
}
Menu autoChoser;
/**
 * The menus constructor
*/
void initautoChoser(string * itemNames, string * infos){
	autoChoser.itemCount = options;
	autoChoser.selected = 0;
	autoChoser.itemNames = itemNames;
	autoChoser.infos = infos;
}

/**
	workaround to robot c not having function pointers
*/
void activateautoChoser(int f){
	switch(autoChoser.selected){
		case 0:
		case 1:
		case 2:
task main()
{
	// Wait for start
	initializeRobot();
	string itemNames[options] = {"# of goals", "Forward/Back", "Bridge Park"};
	string infos[options] = {"", "", "", ""};
	initautoChoser(itemNames, infos);
	clearScreen();
	while(true){
		displayMenu(autoChoser);
		if(pressed(orangebutton)){
			selectNext(autoChoser);
		}

		if(held(leftarrow, 1)){
			activateautoChoser(0);
		}

		else if(held(rightarrow, 1)){
			activateautoChoser(1);
		}
		else {
			activateautoChoser(-1);
		}

		updateButtons();
	}
	waitForStart();
	//int autoCount;
	//int distToMove;
	// Drive to pendulum goal
	motor[LiftFlagMtr] = 100; //Raise the BSM
	ClearTimer(T1);
	reset();
	drive(60);

	while(!aligned() || time1[T1] <= 3500){
		if(aligned()){
			driveTurns = nMotorEncoder[RightDr];
			pause();
		}
		if(time1[T1] >= 3500){
			motor[LiftFlagMtr] = 0;
		}
	}
	motor[LiftFlagMtr] = 0;
// Drive to pendulum
turnTime(700, -100);
wait1Msec(100);
move(7, 40);
// Score the block
scoreBlocks();
// Drive to ramp
move(-7, -40);// Back away from the goal
motor[LiftFlagMtr] = -100;// Begin to lower the BSM
wait1Msec(100);
turnTime(650, 100);
moveRotations(-driveTurns+4, -80);
turnTime(500, -100);
motor[LiftFlagMtr] = DCstop;// Stop lowering the BSM
move(40, 80);
turnTime(250, 100);
move(40, 80); // Drive onto the ramp



}
