#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     AutoIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     PaddleLIGHT,    sensorLightActive)
#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     AutoIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     BlockEOPD,      sensorAnalogActive)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Includes consts.c and robot.c, as well
// Drivers can be found in Google Drive
#include "actions.h"
int driveTurns;
/**
* returns true if the robot is aligned with the beacon
*/
bool aligned(){
	return SensorValue[AutoIR] == irZone;
}
task main()
{
	// Wait for start
	initializeRobot();
	waitForStart();
	int autoCount;
	int distToMove;
	//Drive to pendulum goal
	motor[LiftFlagMtr] = 100; //Raise the BSM
	ClearTimer(T1);
	reset();
	drive(50);

	bool seenIR = false;

	while(!seenIR || time1[T1] <= 3500){
		if(aligned()){
			seenIR = true;
			driveTurns = nMotorEncoder[RightDr];
			pause();
		}
		if(time1[T1] >= 3500){
			motor[LiftFlagMtr] = 0;
		}
	}
	motor[LiftFlagMtr] = 0;
	// Drive to pendulum
	turnTime(650, -100);
  //motor[LeftDr] = 50;
  //wait1Msec(100);
  //motor[LeftDr] = DCstop;
	wait1Msec(100);
	move(10, 40);
	wait1Msec(100);
	// Score the block
	scoreBlocks();
	// Drive to ramp
	move(-9, -40);// Back away from the goal
	motor[LiftFlagMtr] = -100;// Begin to lower the BSM
	wait1Msec(100);
	//motor[LeftDr] = -50;
 // wait1Msec(100);
 // motor[LeftDr] = DCstop;
  turn(40);
	while (!aligned()){}
	pause();
	moveRotations(-driveTurns + 720, -80);
	wait1Msec(100);
	turnTime(720, -100);
	motor[LiftFlagMtr] = DCstop;// Stop lowering the BSM
	move(40, 80);
	turnTime(450, 100);
	move(60, 80); // Drive onto the ramp
}
