#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     AutoIR,         sensorI2CCustom)
#pragma config(Sensor, S4,     PaddleLIGHT,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robot.c"
#include "joystickdriver.c"

task main()
{
	initializeRobot();
	waitForStart();
	
	//drive to basket
	motor[LiftFlagMtr] = 100;
	wait1Msec(2000);
	
	move(20,80);
	move(7, 40);
	motor[LiftFlagMtr] = 0;
	
	//dump block
	motor[PaddleMtr] = 10;
	wait1Msec(2000);
	motor[PaddleMtr] = -10;
	wait1Msec(2000);
	motor[PaddleMtr] = DCstop;
	
	//lower lift
	motor[LiftFlagMtr] = -100;
	
	//move onto bridge
	move(-4,-80);
	//point(-90, 100);
	turn(-50);
	wait1Msec(800);
	move(26, 80);
	motor[LiftFlagMtr] = DCstop;
	//point(90, 100);
	turn(50);
	wait1Msec(850);
	move(36, 80);
	turn(50);
	wait1Msec(750);
	move(48, 80);
	
	stopRobot();
}
