#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     BlockEOPD,      sensorAnalogActive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tMUXSensor Light = msensor_S4_1;
const tMUXSensor Light2 = msensor_S4_2;
const tMUXSensor AutoIR = msensor_S4_3;

// Includes consts.c and robot.c, as well
// Drivers can be found in Google Drive
#include "actions.h"
int driveTurns;
#define options 3
typedef string strArray[options];
int numberOfGoals = 0;
int bridgeSpot = 0;
bool forwardBackward = false; //back = false
/**
* returns true if the robot is aligned with the beacon
*/
bool aligned(){
	return SensorValue[AutoIR] == irZone || nMotorEncoder[RightDr] > distanceBetweenPend*(numberOfGoals + 1);
}
Menu autoChooser;
/**
* The menus constructor
*/
void initautoChooser(strArray itemNames, strArray infos){
	autoChooser.itemCount = options;
	autoChooser.selected = 0;
	for(int i = 0; i < options; i++){
		autoChooser.itemNames[i] = itemNames[i];
		autoChooser.infos[i] = infos[i];
	}
}

/**
workaround to robot c not having function pointers
*/
void activateautoChooser(int f){
	switch(autoChooser.selected){
		case 0:
			switch (f){
				case 0:
					numberOfGoals--;
					break;
				case 1:
					numberOfGoals++;
					break;
			}
			numberOfGoals %= 4;
			if(numberOfGoals < 0){
				numberOfGoals += 4;
			}
			//*autoChooser.infos = numberOfGoals+1;
			StringFormat(autoChooser.infos[0], "%d", numberOfGoals+1);
			break;
		case 1:
			forwardBackward = !forwardBackward;
			autoChooser.infos[1] = forwardBackward ? "Forward" : "Backward";
			break;
		case 2:
			switch (f){
				case 0:
					bridgeSpot--;
					break;
				case 1:
					bridgeSpot++;
					break;
				case 2:
					bridgeSpot -= 10;
					break;
				case 3:
					bridgeSpot += 10;
					break;
			}
			StringFormat(autoChooser.infos[2], "%d", bridgeSpot);
			break;
	}
}

/**
	raises the lift
*/
task raiseLift(){
	lift(100, 3500);
}

/**
	lowers the lift
*/
task lowerLift(){
	lift(100, 4500);
}

task main()
{
	// Wait for start
	initializeRobot();
	string itemNames[options] = {"Max Goals", "Dir", "Bridge Park"};
	string infos[options] = {"1", "Backward", "0"};
	initautoChooser(itemNames, infos);

	clearScreen();
	while(!held(orangebutton, 2000)){
		displayMenu(autoChooser);
		if(pressed(orangebutton)){
			selectNext(autoChooser);
		}

		if(pressed(leftarrow)){
			activateautoChooser(0);
		}

		else if(pressed(rightarrow)){
			activateautoChooser(1);
		}

		else if(held(leftarrow, 1000)){
			wait1Msec(500);
			if(held(leftarrow, 1000)){
				activateautoChooser(2);
			}
		}

		else if(held(rightarrow, 1000)){
			wait1Msec(500);
			if(held(rightarrow, 1000)){
				activateautoChooser(3);
			}
		}

		updateButtons();
	}
	clearScreen();
	nxtDisplayCenteredBigTextLine(3, "Ready!");
	waitForStart();
	//int autoCount;
	//int distToMove;
	// Drive to pendulum goal
	motor[LiftFlagMtr] = 100; //Raise the BSM
	ClearTimer(T1);
	reset();
	drive(60);

	while(!aligned() || time1[T1] <= 3500){
		if(aligned()){
			driveTurns = nMotorEncoder[RightDr];
			pause();
		}
		if(time1[T1] >= 3500){
			motor[LiftFlagMtr] = 0;
		}
	}
	motor[LiftFlagMtr] = 0;
	// Drive to pendulum
	turnTime(700, -100);
	wait1Msec(100);
	move(7, 40);
	// Score the block
	scoreBlocks();
	// Drive to ramp
	move(-7, -40);// Back away from the goal
	StartTask(lowerLift);// Begin to lower the BSM
	wait1Msec(100);
	turnTime(650, 100);
	moveRotations((forwardBackward ? pendulumLength : 4)-driveTurns, -80);
	turnTime(500, -100);
	move(40+bridgeSpot, 80);
	turnTime(250, 100);
	move((forwardBackward ? -1 : 1)*40, 80); // Drive onto the ramp
}
