#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     driveR,        tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveL,        tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     launcher,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftL,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    goal,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2, 		gate,								tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "consts.h"
#include "actions.h"

//3rd party sensors at some point

task main(){
	initializeRobot();
	waitForStart();
	driveDist(distOffRamp); //get off of ramp
	raiseNet();
	turnDegrees(degreesToCenter);
	driveDist(distToCenter);
	launchOn();
	gateUp();










}
