#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     AutoIR,         sensorI2CCustom)
#pragma config(Sensor, S4,     PaddleLIGHT,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, PIDControl, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Includes consts.c and robot.c, as well
#include "actions.h"
#include "joystickdriver.c"
#include "3rd Party Sensor Drivers/drivers/hitechnic-eopd.h"
#include "3rd Party Sensor Drivers/drivers/hitechnic-irseeker-v2.h"
int driveTurns;
/**
* returns true if the robot is aligned with the beacon
*/
bool aligned(){
	return nMotorEncoder[RightDr] > 1440*24/robot.wheel.circumference*robot.wheel.dRatio;
}
task main()
{
	// Wait for start
	initializeRobot();
	waitForStart();
	// Drive to goal
	motor[LiftFlagMtr]=100;
	ClearTimer(T1);
	reset();
	drive(60);

	while(!aligned() || time1[T1] <= 3500){
		if(aligned()){
			driveTurns = nMotorEncoder[RightDr];
			pause();
		}
		if(time1[T1] >= 3500){
			motor[LiftFlagMtr]=0;
		}
	}
	motor[LiftFlagMtr]=0;
	// Find IR Beacon5

	// Drive to pendulum
	turn(-100);
	wait1Msec(700);
	pause();
	wait1Msec(100);
	move(10, 40);
	// Score Block
	scoreBlocks();
//return;
	// Drive to ramp
	move(-7, -40);
	motor[LiftFlagMtr]=-100;
	wait1Msec(100);
	turn(100);
	wait1Msec(650);
	pause();
	moveRotations(-driveTurns+4, -80);
	turn(-100);
	wait1Msec(500);
	pause();
	motor[LiftFlagMtr]=DCstop;
	move(40, 80);
	turn(100);
	wait1Msec(250);
	pause();
	move(40, 80); // should be 80-20



}
