#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Motor,  mtr_S1_C3_1,     using,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define ever (;;)
task main()
{
clearTimer(0);
	for ever{
		float sine = sin(((float)(time1[0]%40000)/40000.0) * (2.0*PI));
		motor[using] = 80.0 * pow(abs(sine), 1.0/7.0) * sine/abs(sine);
	}
}
