#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     BlockEOPD,      sensorAnalogActive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/hitechnic-eopd.h"
#include "joystickdriver.c"
#include "consts.c"
#include "robot.c"
#include "actions.h"

const tMUXSensor Light = msensor_S4_1;
const tMUXSensor Light2 = msensor_S4_2;

void drive(int rightSpeed, int leftSpeed);
void sit ();

task main ()
{
   //waitForStart();
  
   //drive in front of goals until beacon found
   drive(50,50);
	
   while(SensorValue[AutoIR]!=8)
    {
		
    }
  
    sit();
    drive(-50,50);
   
   //turn until facing toward goal with IR beacon
   while(SensorValue[AutoIR]!=5)
    {
		
    }
  
    sit();
    drive(50,50);
  
   //move until less than 10cm from goal
   while(SensorValue[Sonar]>=10)
    {
  	
    }
   sit();
  
   //drop block into goal
  
   //backup and go to bridge
}

//takes two motor powers and makes the robot drive
void drive(int rightSpeed, int leftSpeed)
 {
  motor[RightDr]=rightSpeed;
  motor[LeftDr]=leftSpeed;
 }

//stops both drive motors
void sit()
 {
  motor[RightDr]=0;
  motor[LeftDr]=0;
}
