#pragma config(Sensor, S1,     gyro,           sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//NOTE: the angle reading might be off by a constant factor (it changes
//depending on how level the sensor is mounted relative to the ground and mabye some other factors)

//The difference between a rectanglular and trapezoidal approxomantion
//is negligable if the update rate is fixed (125 Hz was used for
//testing), there is a small noticable difference at an unfixed rate, but it
//is unclear which approxomation is more accurate

task main()
{
    for(;;)
    {
        wait1Msec(1000);
        const int itts = 200;
        float offset = 0;
        for(int i = 0; i < itts; i++)
        {
            offset += sensorValue[gyro];

            wait1Msec(5);
        }
        offset /= itts;
        //offset = 585;

        float current_speed = 0;
        float previous_speed = 0;
        
        float angle_trap = 0;
        float angle_rect = 0;
        clearTimer(T1);
        while(nNxtButtonPressed != 3)
        {            
            float dt = time1[T1]/(1000.0);
            clearTimer(T1);
                    
            current_speed = sensorValue[gyro]-offset;
            angle_rect += dt*(current_speed); //rectangular approx.
            angle_trap += dt*(current_speed+previous_speed)/2.0; //trapezoidal approx.
            previous_speed = current_speed;

	    int line = 0;
	    displayTextLine(line++, "offset: %4f", offset);
	    displayTextLine(line++, "extra raw: %i", sensorRaw[gyro]); //seems the same as SensorValue
	    displayTextLine(line++, "raw: %i", sensorValue[gyro]);
	    displayTextLine(line++, "rotation: %4f", sensorValue[gyro]-offset);
	    displayTextLine(line++, "rect: %4f", angle_rect);
	    displayTextLine(line++, "trap: %4f", angle_trap);

	    //wait1Msec((8-T1)%8); wait exactly 8 ms has passed since last update
        }
    }
}
