#pragma config(Sensor, S1,     gyro,           sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "3rd Party Sensor Drivers\drivers\hitechnic-gyro.h"

task main()
{
  for(;;)
  {
    wait1Msec(1000);
    const int itts = 200;
    float offset = 0;
    for(int i = 0; i < itts; i++)
    {
      offset += sensorValue[gyro];

      wait1Msec(5);
    }
    offset /= itts;
    //offset = 585;

    float angle = 0;
    clearTimer(T1);
	  while(nNxtButtonPressed != 3)
	  {
	    angle += time1[T1]*(sensorValue[gyro]-offset)/1000.0;
	    clearTimer(T1);

	    int line = 0;
	    displayTextLine(line++, "offset: %4f", offset);
	    displayTextLine(line++, "extra raw: %i", sensorRaw[gyro]); //seems the same as SensorValue
	    displayTextLine(line++, "raw: %i", sensorValue[gyro]);
	    displayTextLine(line++, "rotation: %4f", sensorValue[gyro]-offset);
	    displayTextLine(line++, "anlge: %4f", angle);
	    //wait1Msec(100); //this makes the reading less stable as expected
	  }
	}
}
