#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     BlockEOPD,      sensorAnalogActive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
#include "consts.c"
#include "robot.c"
#include "actions.h"
#include "lego-light.h"

const tMUXSensor AutoIR = msensor_S4_3;
const tMUXSensor Light = msensor_S4_1;
const tMUXSensor Light2 = msensor_S4_2;
task main()
{
	HTSMUXsetAnalogueActive(msensor_S4_1);
	SensorValue(Light) = true;
	SensorValue(Light2) = true;
	LSsetActive(Light);
	LSsetActive(Light2);
	clearScreen();
	while (true){
		int IRValue = SensorValue[AutoIR];
		nxtDisplayTextLine(1, "IR = %d", IRValue);
		nxtDisplayTextLine(2, "PaddleEOPD = %d", HTEOPDreadProcessed(PaddleEOPD));
		nxtDisplayTextLine(3, "BlockEOPD = %d", HTEOPDreadProcessed(BlockEOPD));
		nxtDisplayTextLine(4, "Light = %d", LSvalNorm(Light));
		nxtDisplayTextLine(5, "Light2 = %d", LSvalNorm(Light2));
		nxtDisplayTextLine(4, "Light = %d", LSvalRaw(Light));
		nxtDisplayTextLine(5, "Light2 = %d", LSvalRaw(Light2));
	}
}
