#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     AutoIR,         sensorI2CCustom)
#pragma config(Sensor, S4,     PaddleLIGHT,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robot.c"

task main()
{
	initializeRobot();
	eraseDisplay(); //Clear the NXT screen
	bDisplayDiagnostics = false; //Takes control away from FCS
	bNxtLCDStatusDisplay = false; //Takes control away from NXT firmware
	float dist = -24;
	int prevButton;
	
	while(nNxtButtonPressed != orangebutton){
		nxtDisplayCenteredTextLine(1, "%d", dist);
		if(nNxtButtonPressed == leftarrow) {
			if(prevButton == leftarrow){
				if(time1[T1] > 1000){
					dist -= 10;
					xtDisplayCenteredTextLine(1, "%d", dist);
					wait1Msec(250);
				}
			}else{
				dist--;
				ClearTimer(T1);
				
			}

		}
		if(nNxtButtonPressed == rightarrow){
			if(prevButton == rightarrow){
				if(time1[T1] > 1000){
					dist += 10;
					nxtDisplayCenteredTextLine(1, "%d", dist);
					wait1Msec(250);
				}
			}else{
				dist++;
				ClearTimer(T1);
				
			}
		}
		prevButton = nxtButtonPressed
	}
	
	waitForStart();
	move(dist, (dist > 0) ? 80 : -80);
}
