#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     BlockEOPD,      sensorAnalogActive)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "robot.c"
#include "actions.h"

float dist = -64;

task main()
{
	initializeRobot();
	clearScreen();

	while(!held(orangebutton, 1000)){
		nxtDisplayCenteredTextLine(3, "Distance: %d", dist);

		if(pressed(leftarrow)){
			dist--;
		}

		else if(pressed(rightarrow)){
			dist++;
		}

		else if(held(leftarrow, 1000)){
			wait1Msec(500);
			if(held(leftarrow, 1000)){
				dist -= 10;
			}
		}

		else if(held(rightarrow, 1000)){
			wait1Msec(500);
			if(held(rightarrow, 1000)){
				dist += 10;
			}
		}

		updateButtons();
	}

	nxtDisplayCenteredBigTextLine(3, "Ready!");

	waitForStart();
	move(dist, (dist > 0) ? 80 : -80);
}
