<<<<<<< HEAD
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveL,        tmotorTetrix, openLoop, reversed,encoder)
#pragma config(Motor,  mtr_S1_C1_2,     liftL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     launcher,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     driveR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     liftR,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    goal,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    gate,                 tServoStandard)
=======
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     gyro,           sensorNone)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     driveL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_1,     launcher,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_2,     liftL,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C3_1,     driveR,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C3_2,     liftR,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    goal,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    shrub,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C4_3,    net,                  tServoStandard)
>>>>>>> Kyler's-Code
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "menu.h";
#include "actions.h";

int intake_speed = 80;
<<<<<<< HEAD
int launcher_speed = 80;
bool goal_closed = 0;
bool gate_down = 0;
=======
int launcher_speed = 100;
bool goal_closed_control = 0;
bool net_up = 1;
>>>>>>> Kyler's-Code

int debug = 0;

task main()
{
<<<<<<< HEAD
	clearScreen();
	while(1){
		float dt = time1[T1]/1000.0;
		clearTimer(T1);
		int left_lift = 0;
		int right_lift = 0;
		if(doMenuItem("lift up")){
			//lift_position += 1*dt;//Bash
=======
    servo[shrub] = servo_stop;
    servo[net] = net_close;
	clearScreen();

	while(1){
		int left_lift = 0;
		int right_lift = 0;
		char display[16];
		char bat[16];

		sprintf(bat, "Bat: %f V", externalBattery/1000.0);
		displayMenuItem(bat);
		menu_size++;

		//Lift Control
		if(doMenuItem("lift up")){
>>>>>>> Kyler's-Code
			left_lift = 50;
			right_lift = 50;
		}
		if(doMenuItem("lift down")){
			left_lift = -50;
			right_lift = -50;
		}
<<<<<<< HEAD
		if(doMenuItem("left lift up")){
			left_lift = 50;
		}
		if(doMenuItem("right lift up")){
			right_lift = 50;
		}
		motor[liftL] = left_lift;
		motor[liftR] = right_lift;
		//updateLift();
		char blah[16];
		sprintf(blah, "intake %i", intake_speed);
		bool intake_pressed = 0;
		if(doMenuItem(blah)){
=======
		motor[liftL] = left_lift;
		motor[liftR] = right_lift;

		//Intake Control
		sprintf(display, "intake %i", intake_speed);
		bool intake_pressed = 0;
		if(doMenuItem(display)){
>>>>>>> Kyler's-Code
			intake_pressed = 1;
		}
		if(doMenuItem("inc intake") && time1[T2] >= 200){
			clearTimer(T2);
			intake_speed ++;
		}
		if(doMenuItem("dec intake") && time1[T2] >= 200){
			clearTimer(T2);
			-- intake_speed;
		}
<<<<<<< HEAD
		sprintf(blah, "launcher %i", launcher_speed);
		bool launcher_pressed = 0;
		if(doMenuItem(blah)){
=======

		//Launcher Controls
		sprintf(display, "launcher %i", launcher_speed);
		bool launcher_pressed = 0;
		if(doMenuItem(display)){
>>>>>>> Kyler's-Code
			launcher_pressed = 1;
		}
		if(doMenuItem("inc launcher") && time1[T2] >= 200){
			clearTimer(T2);
			launcher_speed ++;
		}
		if(doMenuItem("dec launcher") && time1[T2] >= 200){
			clearTimer(T2);
			-- launcher_speed;
		}
<<<<<<< HEAD
=======

		//Both Intake and Launcher
>>>>>>> Kyler's-Code
		if(doMenuItem("launch/intake")){
			intake_pressed = 1;
			launcher_pressed = 1;
		}
<<<<<<< HEAD
		{
			motor[launcher] = launcher_speed*launcher_pressed;
		}
		{
			motor[intake] = intake_speed*intake_pressed;
		}
		{
			doToggleMenuItem("shut goal lock\0open goal lock", goal_closed);
			servo[goal] = 180 * goal_closed;
		}
		{
			doToggleMenuItem("down gate\0up gate", gate_down); //it's spelled correctly
			servo[gate] = 10 + 108*gate_down;
=======

		{
			if(launcher_pressed)
	        {
	            clearTimer(T4);
	        }
	        motor[launcher] = (float)(clamp(lerp((float)time1[T4]/launcher_slow_time, launcher_speed, 0.0), 0.0, launcher_speed));
		}

        {
			motor[intake] = intake_speed*intake_pressed;
		}

		{
		    //Goal Lock
			doToggleMenuItem("shut goal lock\0open goal lock", goal_closed_control);
			servo[goal] = goal_open + (goal_close-goal_open) * goal_closed_control;
		}
		{
		    //Net
			doToggleMenuItem("open net\0shut net", net_up);
			servo[net] = net_open + (net_close-net_open) * net_up;
>>>>>>> Kyler's-Code
		}
		updateMenu();
	}
}
