#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     driveR,        tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveL,        tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     launcher,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftL,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    goal,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "menu.h";
#include "actions.h";

int intake_speed = 1;
int launcher_speed = 1;

task main()
{
	clearScreen();
	while(1){
		float dt = time1[T1]/1000.0;
		clearTimer(T1);
		if(displayMenuItem("lift")){
			lift_position += 1*dt;//Bash
		}
		char blah[16];
		sprintf(blah, 16, "intake %i", intake_speed);
		if(displayMenuItem(blah)){
			motor[intake] = intake_speed;
		}
		else{
			motor[intake] = 0;
		}
		if(displayMenuItem("increase intake") && time1[T2] >= 100){
			clearTimer(T2);
			intake_speed ++;
		}
		if(displayMenuItem("decrease intake") && time1[T2] >= 100){
			clearTimer(T2);
			-- intake_speed;
		}
		sprintf(blah, 16, "launcher %i", launcher_speed);
		if(displayMenuItem(blah)){
			motor[launcher] = launcher_speed;
		}
		else{
			motor[launcher] = 0;
		}
		if(displayMenuItem("increase launcher") && time1[T2] >= 100){
			clearTimer(T2);
			launcher_speed ++;
		}
		if(displayMenuItem("decrease launcher") && time1[T2] >= 100){
			clearTimer(T2);
			-- launcher_speed;
		}
		if(displayMenuItem("goal lock")){
		}
		updateMenu();
		updateLift();
	}
}
