#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     turboTouch,     sensorTouch)
#pragma config(Sensor, S3,     blank,          sensorTouch)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LiftMtr1,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FlagMtr,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     LiftMtr2,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    Turbofan,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    LeftIntake,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    RightIntake,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "actions.h"
#include "3rd Party Sensor Drivers\drivers\lego-light.h"
#include "joystickdriver.c"

const tMUXSensor LightBack = msensor_S4_1;
const tMUXSensor LightFront = msensor_S4_2;
const tMUXSensor AutoIR = msensor_S4_3;

//#include "consts.c", "robot.c"




Menu resetMenu;

#define options 6
typedef string strArray[options];
/**
 * The menus constructor
*/
void initResetMenu(strArray itemNames, strArray infos){
	resetMenu.itemCount = options;
	resetMenu.selected = 0;
	for(int i = 0; i < options; i++){
		resetMenu.itemNames[i] = itemNames[i];
		resetMenu.infos[i] = infos[i];
	}
}

/**
	workaround to robot c not having function pointers
*/
void activateResetMenu(int f){
	switch(resetMenu.selected){
		case 0: //lift
			switch(f){
				default:
					motor[LiftMtr1] = DCstop;
					motor[LiftMtr2] = DCstop;
					break;
				case 0:
					motor[LiftMtr1] = -100;
					motor[LiftMtr2] = -100;
					break;
				case 1:
					motor[LiftMtr1] = 100;
					motor[LiftMtr2] = 100;
					break;
			}
			break;

		case 1: //flag
			switch(f){default:
					motor[FlagMtr] = 0;
					break;
				case 0:
					motor[FlagMtr]=-100;
					break;
				case 1:
					motor[FlagMtr]=100;
					break;
			}
			break;

		case 2: //turbofan
			switch(f){
				default:
					break;
				case 0:
					servo[Turbofan] += 1;
					break;
				case 1:
					servo[Turbofan] -= 1;
					break;

			}
			break;

		case 3:
			switch(f){
				default:
					motor[Intake] = 0;
				break;
				case 0:
					motor[Intake] = 100;
					break;
				case 1:
					motor[Intake] = -100;
					break;
			}
			break;
		case 4:
			switch(f){
				case 0:
					servo[RightIntake] = 255-intakeOffset;
					servo[LeftIntake] = 0+intakeOffset;
					break;
				case 1:
					servo[RightIntake] = 0;// + intakeOffset;
					servo[LeftIntake] = 255;// - intakeOffset;
			}
			break;
		case 5:
			TFileHandle file;
			TFileIOResult result;
			int fileSize = 16;
			switch(f){
				default:
					break;
				case 2:
					Delete("test.txt", result);
					PlaySound(soundException);
					break;
				case 3:
					OpenWrite(file, result, "test.txt", fileSize);
					WriteLong(file, result, LSvalNorm(LightBack));
					WriteLong(file, result, LSvalNorm(LightFront));
					Close(file, result);
					PlaySound(soundFastUpwardTones);
					break;
			}
			break;
	}
}

void updateResetInfos(){
	StringFormat(resetMenu.infos[5], "%d, %d", LSvalNorm(LightBack), LSvalNorm(LightFront));
}

task main()
{
	HTSMUXsetAnalogueActive(msensor_S4_1);
	HTSMUXsetAnalogueActive(msensor_S4_2);
	string itemNames[options] = {"Lift", "Flag", "Turbofan", "Intake", "Flip Out", "LitCfg"};
	string infos[options] = {"", "", "", "", "", "0"};
	initResetMenu(itemNames, infos);
	clearScreen();
	while(true){
		displayMenu(resetMenu);
		updateResetInfos();
		if(pressed(orangebutton)){
			selectNext(resetMenu);
		}
		else if(pressed(leftarrow)){
			activateResetMenu(2);
		}

		else if(pressed(rightarrow)){
			activateResetMenu(3);
		}
		else if(held(leftarrow, 1)){
			activateResetMenu(0);
		}

		else if(held(rightarrow, 1)){
			activateResetMenu(1);
		}
		else {
			activateResetMenu(-1);
		}

		updateButtons();
	}
}
