#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     turboTouch,     sensorTouch)
#pragma config(Sensor, S3,     blank,          sensorTouch)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LiftMtr1,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FlagMtr,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     LiftMtr2,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    Turbofan,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    LeftIntake,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    RightIntake,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
#include "consts.h"
#include "robot.h"
#include "actions.h"
#include "lego-light.h"

const tMUXSensor LightBack = msensor_S4_1;
const tMUXSensor LightFront = msensor_S4_2;
const tMUXSensor AutoIR = msensor_S4_3;

task main()
{

	clearScreen();
	//StartTask(Paddle);
	while (true){
		getJoystickSettings(joystick);
		HTSMUXsetAnalogueActive(msensor_S4_1);
		HTSMUXsetAnalogueActive(msensor_S4_2);
		nxtDisplayTextLine(1, "IR = %d", HTIRS2readACDir(AutoIR));
		//nxtDisplayTextLine(2, "PaddleEOPD = %d", HTEOPDreadProcessed(PaddleEOPD));
		//nxtDisplayTextLine(3, "BlockEOPD = %d", HTEOPDreadProcessed(BlockEOPD));
		LSsetActive(LightBack);
		nxtDisplayTextLine(4, "LightBack = %d", LSvalNorm(LightBack));
		nxtDisplayTextLine(5, "LightFront = %d", LSvalNorm(LightFront));
		nxtDisplayTextLine(6, "Other IR = %d", HTIRS2readACDir(AutoIR));
	}
}
