#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     PaddleEOPD,     sensorAnalogActive)
#pragma config(Sensor, S3,     BlockEOPD,      sensorAnalogActive)
#pragma config(Motor,  mtr_S1_C1_1,     LiftFlagMtr,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     PaddleMtr,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     RightDr,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LeftDr,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    LeftIntake,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RightIntake,          tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "tele_op_library.h"

/*const tMUXSensor Light = msensor_S4_1;
const tMUXSensor Light2 = msensor_S4_2;
const tMUXSensor AutoIR = msensor_S4_3;
*/
/**
 * REMOTE 1
 *  Left Joystick - Drive
 *  Right Joystick - Paddle (slow variable speed)
 *  Button LB / RB - Paddle forward / reverse (fixed fast speed)
 *  Button LT / RT - Intake forward / reverse
 *  Top Hat, right / left - paddle, one-carriage turn in forward /reverse direction
 *    + button A - slow
 *
 * REMOTE 2
 *  Right Joystick - Lift
 *  Button A - move lift up slightly
 */

task main() {
	initializeRobot();
//	initializeRobotnext();

	waitForStart(); // wait for start of tele-op phase
	StartTask(Paddle);
	while(true){
		getJoystickSettings(joystick);
		liftAndFlag();
		singleJoyDrive();
		Intake();
	}
}
