#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     lf,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     lb,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rf,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rb,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     launcher,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

#define btnX 1
#define btnA 2
#define btnB 3
#define btnY 4

void drive(int leftspeed, int rightspeed) {
	if(abs(leftspeed)>20) {
		motor[lf]=leftspeed;
		motor[lb]=leftspeed;
	}
	else {
		motor[lf]=0;
		motor[lb]=0;
	}
	if(abs(rightspeed)>20) {
		motor[rf]=rightspeed;
		motor[rb]=rightspeed;
	}
	else {
		motor[rf]=0;
		motor[rb]=0;
	}
}

task main()
{
	int left_drive_control;
	int rght_drive_control;

	while(true) {
		getJoystickSettings(joystick);
		left_drive_control = (joystick.joy1_y1 + joystick.joy1_x1)*75/128;
		rght_drive_control = (joystick.joy1_y1 - joystick.joy1_x1)*75/128;
		drive(left_drive_control,rght_drive_control);

		if(joy1Btn(btnY)==1) {motor[intake]=80;}
		else {motor[intake]=0;}
	}
}
