#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     lf,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     lb,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rf,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rb,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     launcher,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"
#include "consts.c"

void drive(int leftspeed, rightspeed) {
	motor[lf]=leftspeed;
	motor[lb]=leftspeed;
	motor[rf]=rightspeed;
	motor[rb]=rightspeed;
}

task main()
{

	wait1Msec(1000);
	drive(0);
}
