#pragma config(Sensor, S1,     US,             sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    float a = 0;
    while(1){
        a = 0.9*a + 0.1*SensorValue(US);
        writeDebugStreamLine("%i", a);
        wait1Msec(8);
    }
}
