#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveL,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joystickdriver.c"

#define sq(a) (a)*(a)

float quadBezier(float t, float p1, float p2, float p3)
{
    return sq(1-t)*p1 + 2.0*t*(1-t)*p2 + sq(t)*p3;
}

static unsigned short prev1Btns = 0;
static unsigned short toggle1Btns = 0;

bool joy1Toggle(unsigned short btn)
{
    return (bool)((toggle1Btns >> (btn-1))&1);
}

//Drive Constants
#define threshold 0.1
#define min_drive 15
#define bezier_drive_control 10
#define max_drive 100

#define left_drive_control (-joystick.joy1_y1 + joystick.joy1_x1)/127.0
#define rght_drive_control (-joystick.joy1_y1 - joystick.joy1_x1)/127.0

// Joystick buttons
#define btnX 1
#define btnA 2
#define btnB 3
#define btnY 4

#define btnLB 5
#define btnRB 6
#define btnLT 7
#define btnRT 8

//Back and Start
#define btnBack 9
#define btnStart 10

#define intakeBtn joy1Toggle(btnRT)
#define intakeReverseBtn joy1Toggle(btnLT)

task main()
{
    waitForStart();
    for(;;)
    {
        prev1Btns = joystick.joy1_Buttons;
        getJoystickSettings(joystick);
        toggle1Btns = (toggle1Btns^((joystick.joy1_Buttons) & (~prev1Btns)));

        float magnitude = sqrt(left_drive_control*left_drive_control+rght_drive_control*rght_drive_control);//the magnitude of the joystick vector
        if(magnitude >= threshold)
        {
            //maximum speed*(the magnitude of the joystick mapped from threshold to 1 to 0 to 1)*(the normalized joystick)
            //= maximum speed*(fraction speed)*(direction)
            float speed = (magnitude-threshold)/(1-threshold);
            speed = quadBezier(speed, min_drive, bezier_drive_control, max_drive);
            int left_vIs = speed*(left_drive_control/magnitude);
            int right_vIs = speed*(rght_drive_control/magnitude);
            motor[driveL] = left_vIs;
            motor[driveR] = right_vIs;
        }
        else
        {
            motor[driveL] = 0;
            motor[driveR] = 0;
        }

        if(intakeBtn)
        {
            motor[motorA] = 100;
            motor[motorB] = 100;
        }
        else if(intakeReverseBtn)
        {
            motor[motorA] = -100;
            motor[motorB] = -100;
        }
        else if(intakeReverseBtn && intakeBtn)
        {
            motor[motorA] = 0;
            motor[motorB] = 0;
        }
        else
        {
            motor[motorA] = 0;
            motor[motorB] = 0;
        }

    }
}
